#!/usr/bin/env bash
set -e
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.sh$|bashrc$' || true)
[ -z "$files" ] && exit 0
if command -v shellcheck >/dev/null 2>&1; then
  echo "$files" | xargs -r shellcheck -x -e SC1090,SC1091,SC2016,SC2154
fi
